# Generated by Django 5.0.3 on 2024-04-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام فرستند')),
                ('massege', models.TextField(verbose_name='پیام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('sunject', models.CharField(max_length=100, verbose_name='موضوع پیام')),
            ],
        ),
    ]
