# Generated by Django 5.0.3 on 2024-04-27 06:59

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_created_alter_comment_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_file', models.ImageField(upload_to='Post_image/')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'تصویر پست',
                'verbose_name_plural': 'تصویر پست ها',
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='blog_imagep_created_5b220d_idx')],
            },
        ),
    ]
