# Generated by Django 5.0.3 on 2024-05-02 07:29

import blog.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_imagepost_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='Image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to=blog.models.upload_to),
        ),
    ]
